---
debug_mode: 0                                   # plot all spectra
object_name: HD123299                           # Target name (useful for Simbad query)
T0: 2451441.804                                 # Fix Periastron epoch T0 if known (julian date)
period:                                         # If the period of the orbit is already known use this param (period in days). 
period_guess: 51                                # If the period is uncertain use this param (period in days).
title: "α Dra - HD123299 - Phased radial velocities"
subtitle: "April 2022 to April 2023 - Star'Ex HR (2400 l/mm)"
binary_star_type: SB1                           # SB1 or SB2
spec_file_regex: '(.*).fit'                           # Fits file pattern
line_color: black                                     # Define the color of the fitted velocity curve
# Define the style of the dots by instruments type 'BSS_INST'
markers_styles: o,v,^,s,D,P,X                         
# Define the color of the dots ex 'red' or a color
# cycle for each observer ex with 3 observers 'red,black,yellow'
markers_colors: purple,red,blue,darkorange,green,cyan,black,slategrey   

radial_velocity_correction: barycentric               # The kind of velocity correction. Must be ‘barycentric’ or ‘heliocentric’.  

lambda_ref: 6562.82                             
model: voigt                                          # gaussian, voigt or lorentz
spectral_region: 10
fwhm: .5
window_width: 1.5

# result options
font_size: 9
title_font_size: 9
font_family: monospace
fig_size_x: 11
fig_size_y: 7
fig_rv_y_multiple: 10
fig_residual_y_multiple: 0.5
dpi: 150
