---
debug_mode: 1                                   # plot all spectra
object_name: HD123299                           # Target name (useful for Simbad query)
period:                                         # If the period of the orbit is already known use this param (period in days). 
period_guess: 51                                # If the period is uncertain use this param (period in days).
title: "α Dra - Phased radial-velocities - observations collected from April 2022 to April 2023"
subtitle: "Star'Ex HR (2400 l/mm) - G. Bertrand & A. Leduc"
binary_star_type: SB1                           # SB1 or SB2
spec_file_regex: '_(.+)_(\d+)_(\d+)(.*).fits'   # Fits file pattern
line_color: black                               # Define the color of the fitted velocity curve
points_color: red,black                         # Define the color of the dots ex 'red' or a color
                                                # cycle for each observer ex with 3 observers 'red,black,yellow'

radial_velocity_correction: barycentric         # The kind of velocity correction. Must be ‘barycentric’ or ‘heliocentric’.  

lambda_ref: 6562.82                             
model: voigt                                    # gaussian, voigt or lorentz
spectral_region: 10
fwhm: .5
window_width: 1.5

# result options
font_size: 9
title_font_size: 9
font_family: monospace
fig_size_x: 9
fig_size_y: 5
dpi: 150
